/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package videorentalstore.gui;

/**
 *
 * @author Ashley
 */
public class CustomerAccount_AccountInfo extends javax.swing.JFrame {

    /**
     * Creates new form CustomerAccount_AccountInfo
     */
    public CustomerAccount_AccountInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        boarder4 = new javax.swing.JPanel();
        rentalsRULogoSmallLabel4 = new javax.swing.JLabel();
        toolBar4 = new javax.swing.JToolBar();
        homeButton4 = new javax.swing.JButton();
        divider9 = new javax.swing.JLabel();
        myAccountButton4 = new javax.swing.JButton();
        divider10 = new javax.swing.JLabel();
        logoutButton4 = new javax.swing.JButton();
        boarderLine4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(43, 45, 44));

        boarder4.setBackground(new java.awt.Color(153, 0, 0));
        boarder4.setAlignmentY(1.0F);

        rentalsRULogoSmallLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/videorentalstore/gui/Image_Rent4ULogoSmall.jpg"))); // NOI18N

        toolBar4.setBackground(new java.awt.Color(153, 0, 0));
        toolBar4.setBorder(null);
        toolBar4.setFloatable(false);
        toolBar4.setRollover(true);
        toolBar4.setBorderPainted(false);

        homeButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        homeButton4.setText("Home");
        homeButton4.setBorderPainted(false);
        homeButton4.setFocusable(false);
        homeButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        homeButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        homeButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButton4ActionPerformed(evt);
            }
        });
        toolBar4.add(homeButton4);

        divider9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        divider9.setText("  |  ");
        toolBar4.add(divider9);

        myAccountButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        myAccountButton4.setText("My Account");
        myAccountButton4.setFocusable(false);
        myAccountButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        myAccountButton4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        myAccountButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myAccountButton4ActionPerformed(evt);
            }
        });
        toolBar4.add(myAccountButton4);

        divider10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        divider10.setText("  |  ");
        toolBar4.add(divider10);

        logoutButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logoutButton4.setText("Logout");
        logoutButton4.setFocusable(false);
        logoutButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logoutButton4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        logoutButton4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        logoutButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButton4ActionPerformed(evt);
            }
        });
        toolBar4.add(logoutButton4);

        boarderLine4.setBackground(new java.awt.Color(0, 0, 0));
        boarderLine4.setPreferredSize(new java.awt.Dimension(0, 5));

        javax.swing.GroupLayout boarderLine4Layout = new javax.swing.GroupLayout(boarderLine4);
        boarderLine4.setLayout(boarderLine4Layout);
        boarderLine4Layout.setHorizontalGroup(
            boarderLine4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        boarderLine4Layout.setVerticalGroup(
            boarderLine4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout boarder4Layout = new javax.swing.GroupLayout(boarder4);
        boarder4.setLayout(boarder4Layout);
        boarder4Layout.setHorizontalGroup(
            boarder4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boarder4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rentalsRULogoSmallLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1310, Short.MAX_VALUE)
                .addComponent(toolBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(boarderLine4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1777, Short.MAX_VALUE)
        );
        boarder4Layout.setVerticalGroup(
            boarder4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boarder4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(boarder4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rentalsRULogoSmallLabel4)
                    .addComponent(toolBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(boarderLine4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/videorentalstore/gui/Image_AccountInfoLabel.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(boarder4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(boarder4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(0, 823, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButton4ActionPerformed
        dispose();
        CustomerAccount_Movies f = new CustomerAccount_Movies();
        f.setVisible(true);
    }//GEN-LAST:event_homeButton4ActionPerformed

    private void myAccountButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myAccountButton4ActionPerformed
        dispose();
        CustomerAccount_MyAccount f = new CustomerAccount_MyAccount();
        f.setVisible(true);
    }//GEN-LAST:event_myAccountButton4ActionPerformed

    private void logoutButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButton4ActionPerformed
        dispose();
    }//GEN-LAST:event_logoutButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerAccount_AccountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerAccount_AccountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerAccount_AccountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerAccount_AccountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerAccount_AccountInfo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boarder;
    private javax.swing.JPanel boarder1;
    private javax.swing.JPanel boarder2;
    private javax.swing.JPanel boarder3;
    private javax.swing.JPanel boarder4;
    private javax.swing.JPanel boarderLine;
    private javax.swing.JPanel boarderLine1;
    private javax.swing.JPanel boarderLine2;
    private javax.swing.JPanel boarderLine3;
    private javax.swing.JPanel boarderLine4;
    private javax.swing.JLabel divider1;
    private javax.swing.JLabel divider10;
    private javax.swing.JLabel divider2;
    private javax.swing.JLabel divider3;
    private javax.swing.JLabel divider4;
    private javax.swing.JLabel divider5;
    private javax.swing.JLabel divider6;
    private javax.swing.JLabel divider7;
    private javax.swing.JLabel divider8;
    private javax.swing.JLabel divider9;
    private javax.swing.JButton homeButton;
    private javax.swing.JButton homeButton1;
    private javax.swing.JButton homeButton2;
    private javax.swing.JButton homeButton3;
    private javax.swing.JButton homeButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton logoutButton1;
    private javax.swing.JButton logoutButton2;
    private javax.swing.JButton logoutButton3;
    private javax.swing.JButton logoutButton4;
    private javax.swing.JButton myAccountButton;
    private javax.swing.JButton myAccountButton1;
    private javax.swing.JButton myAccountButton2;
    private javax.swing.JButton myAccountButton3;
    private javax.swing.JButton myAccountButton4;
    private javax.swing.JLabel rentalsRULogoSmallLabel;
    private javax.swing.JLabel rentalsRULogoSmallLabel1;
    private javax.swing.JLabel rentalsRULogoSmallLabel2;
    private javax.swing.JLabel rentalsRULogoSmallLabel3;
    private javax.swing.JLabel rentalsRULogoSmallLabel4;
    private javax.swing.JToolBar toolBar;
    private javax.swing.JToolBar toolBar1;
    private javax.swing.JToolBar toolBar2;
    private javax.swing.JToolBar toolBar3;
    private javax.swing.JToolBar toolBar4;
    // End of variables declaration//GEN-END:variables
}
